### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'git')

### ISSUE THREAD

**Issue by nightire** [axetroy/vscode-gpm#337]
Clone a repo from GitHub throws an error that seems related to git. Below are the error logs:

```
clone project 'https://github.com/xxx/xxx.git'
parse git info '{
  "protocols": [
    "https"
  ],
  "protocol": "https",
  "port": null,
  "resource": "github.com",
  "user": "",
  "pathname": "/xxx/xxx.git",
  "hash": "",
  "search": "",
  "href": "https://github.com/xxx/xxx.git",
  "query": {},
  "token": "",
  "source": "github.com",
  "git_suffix": true,
  "name": "xxx",
  "owner": "xxx",
  "ref": "",
  "filepathtype": "",
  "filepath": "",
  "organization": "xxx",
  "full_name": "xxx/xxx"
}'
temp dir '/var/folders/5b/q0vzlh5n23v0051bdhhxv6200000gn/T/gpm/temp/245a795a4f9fa026015b3ee37ea59305'
TypeError: Cannot read properties of undefined (reading 'git')
    at jo.<anonymous> (/Users/xxx/.vscode/extensions/axetroy.vscode-gpm-2.7.8/out/index.js:50:14034)
    at Generator.next (<anonymous>)
    at /Users/xxx/.vscode/extensions/axetroy.vscode-gpm-2.7.8/out/index.js:1:1186
    at new Promise (<anonymous>)
    at q (/Users/xxx/.vscode/extensions/axetroy.vscode-gpm-2.7.8/out/index.js:1:1006)
    at jo.getGitAPI (/Users/xxx/.vscode/extensions/axetroy.vscode-gpm-2.7.8/out/index.js:50:13750)
    at jo.<anonymous> (/Users/xxxx/.vscode/extensions/axetroy.vscode-gpm-2.7.8/out/index.js:50:15307)
    at Generator.next (<anonymous>)
    at f (/Users/xxx/.vscode/extensions/axetroy.vscode-gpm-2.7.8/out/index.js:1:1044)
```

**Comment by nightire** [comment]
@axetroy Hello, would you be willing to take a look at this issue?
